;(function () {
'use strict';

/* ---- Loading ---- */
window.addEventListener('load', function () {
  var loading = document.getElementById('loading');
  if (loading) {
    loading.classList.add('done');
    setTimeout(function () { loading.remove(); }, 800);
  }
});

/* ---- Header scroll effect ---- */
var header = document.getElementById('header');
var main = document.querySelector('main');

if ('scrollRestoration' in window.history) {
  window.history.scrollRestoration = 'manual';
}

/* ---- Complete-source crop settings saved by avatar-crop.html ---- */
var cropStorageKey = 'aboutme.imageCrops.v1';
var cropTargets = {
  avatar: { selector: '.nav .nav-logo img', positionX: 0.5, positionY: 0.5 },
  about: { selector: '.about-photo img', positionX: 0.5, positionY: 0.5 },
  perception: { selector: '.work-img--perception img', positionX: 0.5, positionY: 0.38 },
  '12dof': { selector: '.work-img--12dof img', positionX: 0.5, positionY: 1 },
  '8dof': { selector: '.work-img--8dof img', positionX: 0.5, positionY: 0.53 },
  arm: { selector: '.work-img--arm img', positionX: 0.5, positionY: 0.5 }
};
var savedImageCrops = {};

try {
  savedImageCrops = JSON.parse(localStorage.getItem(cropStorageKey)) || {};
} catch (error) {
  savedImageCrops = {};
}
if (!savedImageCrops || typeof savedImageCrops !== 'object' || Array.isArray(savedImageCrops)) {
  savedImageCrops = {};
}

/* Ignore the first unified tool's overly wide 8DOF default framing. */
if (
  savedImageCrops['8dof'] &&
  Number(savedImageCrops['8dof'].x) === 0 &&
  Number(savedImageCrops['8dof'].y) === 0 &&
  Number(savedImageCrops['8dof'].scale) === 1
) {
  delete savedImageCrops['8dof'];
}

function normalizedCrop(candidate) {
  if (!candidate) return null;
  var cropX = Number(candidate.x);
  var cropY = Number(candidate.y);
  var cropScale = Number(candidate.scale);
  if (
    !Number.isFinite(cropX) ||
    !Number.isFinite(cropY) ||
    !Number.isFinite(cropScale) ||
    cropScale < 1 || cropScale > 3
  ) return null;

  return {
    x: Math.min(200, Math.max(-200, cropX)),
    y: Math.min(200, Math.max(-200, cropY)),
    scale: cropScale
  };
}

/* Keep crop settings made with the earlier avatar-only version. */
if (!normalizedCrop(savedImageCrops.avatar)) {
  try {
    var legacyAvatarCrop = normalizedCrop(
      JSON.parse(localStorage.getItem('aboutme.avatarCrop.v1'))
    );
    if (legacyAvatarCrop) savedImageCrops.avatar = legacyAvatarCrop;
  } catch (error) {
    /* Keep the CSS avatar defaults if legacy storage is unavailable. */
  }
}

var cropParams = new URLSearchParams(window.location.search);
var queryTarget = cropParams.get('cropTarget');
var queryCrop = normalizedCrop({
  x: cropParams.get('cropX'),
  y: cropParams.get('cropY'),
  scale: cropParams.get('cropScale')
});
var hasQueryCrop = (
  Object.prototype.hasOwnProperty.call(cropTargets, queryTarget) &&
  cropParams.has('cropX') &&
  cropParams.has('cropY') &&
  cropParams.has('cropScale') &&
  queryCrop
);

/* Also accept links generated by the earlier avatar-only tool. */
if (!hasQueryCrop && cropParams.has('avatarX') && cropParams.has('avatarY') && cropParams.has('avatarScale')) {
  queryTarget = 'avatar';
  queryCrop = normalizedCrop({
    x: cropParams.get('avatarX'),
    y: cropParams.get('avatarY'),
    scale: cropParams.get('avatarScale')
  });
  hasQueryCrop = Boolean(queryCrop);
}

if (hasQueryCrop) {
  savedImageCrops[queryTarget] = queryCrop;
  try {
    localStorage.setItem(cropStorageKey, JSON.stringify(savedImageCrops));
  } catch (error) {
    /* URL parameters still provide the current preview when storage is unavailable. */
  }
}

var cropImages = [];

function layoutCropImage(entry) {
  var image = entry.image;
  var config = entry.config;
  var frame = image.parentElement;
  if (!frame || !image.complete || !image.naturalWidth) return;

  var frameWidth = frame.clientWidth;
  var frameHeight = frame.clientHeight;
  if (!frameWidth || !frameHeight) return;

  var coverScale = Math.max(
    frameWidth / image.naturalWidth,
    frameHeight / image.naturalHeight
  );
  var renderedWidth = image.naturalWidth * coverScale;
  var renderedHeight = image.naturalHeight * coverScale;
  var baseCenterX = (
    (frameWidth - renderedWidth) * config.positionX + renderedWidth / 2
  );
  var baseCenterY = (
    (frameHeight - renderedHeight) * config.positionY + renderedHeight / 2
  );

  image.style.setProperty('--crop-source-width', renderedWidth + 'px');
  image.style.setProperty('--crop-source-height', renderedHeight + 'px');
  image.style.setProperty('--crop-base-left', baseCenterX + 'px');
  image.style.setProperty('--crop-base-top', baseCenterY + 'px');
  image.classList.add('crop-layout-ready');
}

function layoutAllCropImages() {
  cropImages.forEach(layoutCropImage);
}

Object.keys(cropTargets).forEach(function (targetKey) {
  var config = cropTargets[targetKey];
  var image = document.querySelector(config.selector);
  if (!image) return;

  var savedCrop = normalizedCrop(savedImageCrops[targetKey]);
  if (savedCrop) {
    image.style.setProperty('--crop-x', savedCrop.x + '%');
    image.style.setProperty('--crop-y', savedCrop.y + '%');
    image.style.setProperty('--crop-scale', savedCrop.scale);
  }

  var entry = { image: image, config: config };
  cropImages.push(entry);
  image.addEventListener('load', function () { layoutCropImage(entry); });
  if (image.complete) layoutCropImage(entry);
});

window.addEventListener('resize', function () {
  window.requestAnimationFrame(layoutAllCropImages);
});

if (header && main) {
  main.addEventListener('scroll', function () {
    header.classList.toggle('scrolled', main.scrollTop > 80);
  });
}

/* A tool jump may target one section once; an ordinary reload always starts at hero. */
var navigationEntry = window.performance && window.performance.getEntriesByType
  ? window.performance.getEntriesByType('navigation')[0]
  : null;
var isPageReload = navigationEntry
  ? navigationEntry.type === 'reload'
  : Boolean(window.performance && window.performance.navigation && window.performance.navigation.type === 1);
var initialSectionHash = isPageReload ? '' : window.location.hash;

function setMainScrollPosition(top) {
  if (!main) return;
  var previousScrollBehavior = main.style.scrollBehavior;
  main.style.scrollBehavior = 'auto';
  main.scrollTop = top;
  window.requestAnimationFrame(function () {
    main.style.scrollBehavior = previousScrollBehavior;
  });
}

function scrollMainToHash(hashValue) {
  if (!main || !hashValue) return false;
  var hashTarget = document.querySelector(hashValue);
  if (hashTarget && main.contains(hashTarget)) {
    hashTarget.querySelectorAll('img[loading="lazy"]').forEach(function (image) {
      image.loading = 'eager';
    });
    setMainScrollPosition(hashTarget.offsetTop);
    hashTarget.querySelectorAll('.fade-up').forEach(function (element) {
      element.classList.add('in');
    });
    return true;
  }
  return false;
}

function applyInitialScrollPosition() {
  if (!scrollMainToHash(initialSectionHash)) {
    setMainScrollPosition(0);
  }
}

function cleanTransientNavigationUrl() {
  var cleanUrl = new URL(window.location.href);
  var transientParameters = [
    'cropTarget', 'cropX', 'cropY', 'cropScale', 'cropPreview',
    'avatarX', 'avatarY', 'avatarScale', 'avatarPreview'
  ];
  var changed = Boolean(cleanUrl.hash);

  cleanUrl.hash = '';
  transientParameters.forEach(function (name) {
    if (cleanUrl.searchParams.has(name)) {
      cleanUrl.searchParams.delete(name);
      changed = true;
    }
  });

  if (changed) {
    window.history.replaceState(window.history.state, '', cleanUrl.href);
  }
}

applyInitialScrollPosition();
cleanTransientNavigationUrl();
window.addEventListener('load', function () {
  applyInitialScrollPosition();
  window.setTimeout(applyInitialScrollPosition, 0);
});
window.addEventListener('hashchange', function () {
  scrollMainToHash(window.location.hash);
});

/* ---- IntersectionObserver: fade-up ---- */
var observer = new IntersectionObserver(function (entries) {
  entries.forEach(function (entry) {
    if (entry.isIntersecting) {
      entry.target.classList.add('in');
    }
  });
}, { root: main, threshold: 0.15 });

document.querySelectorAll('.fade-up').forEach(function (el) {
  observer.observe(el);
});

/* ---- Smooth scroll for page links ---- */
document.querySelectorAll('a[href^="#"]').forEach(function (a) {
  a.addEventListener('click', function (e) {
    var target = document.querySelector(this.getAttribute('href'));
    if (target && main) {
      e.preventDefault();
      main.scrollTo({ top: target.offsetTop, behavior: 'smooth' });
    }
  });
});

/* ---- Nav active section highlight ---- */
if (main) {
  var sections = document.querySelectorAll('.section[id]');
  var navLinks = document.querySelectorAll('.nav a[href^="#"]');

  main.addEventListener('scroll', function () {
    var scrollY = main.scrollTop + 120;
    var currentId = '';

    sections.forEach(function (section) {
      if (section.offsetTop <= scrollY) {
        currentId = section.id;
      }
    });

    navLinks.forEach(function (link) {
      var href = link.getAttribute('href').slice(1);
      link.style.color = href === currentId
        ? 'rgba(255,255,255,.9)'
        : 'rgba(255,255,255,.6)';
    });
  });
}

/* ---- Keyboard: ESC to stop scroll snap ---- */
document.addEventListener('keydown', function (e) {
  if (e.key === 'Escape' && main) {
    main.style.scrollSnapType = 'none';
  }
});

})();
